function StereoParams = StereoCalibration()

% Define images to process
imageFileNames1 = {'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_01.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_02.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_03.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_04.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_05.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_06.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_07.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_08.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_09.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_10.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_11.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_12.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_13.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_15.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_17.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_18.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_19.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_20.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib\frame_C0_21.png',...
    };
imageFileNames2 = {'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_01.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_02.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_03.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_04.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_05.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_06.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_07.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_08.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_09.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_10.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_11.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_12.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_13.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_15.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_17.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_18.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_19.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_20.png',...
    'C:\Users\Daniel\Desktop\Class Files\Project\calib2\frame_C1_21.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

% Generate world coordinates of the checkerboard keypoints
squareSize = 2.775000e+01;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% You can use the calibration data to rectify stereo images.
I2 = imread(imageFileNames2{1});
[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);
StereoParams = stereoParams;
end
